### ISSUE TITLE
Use new meetup logo icon

### ISSUE THREAD

**Issue by caseywatts** [NoVACodeCoffee/novacodecoffee.github.io#10]
fontawesome has it included
dccodecoffee has done this, you can look there for reference.

**Comment by caseywatts** [comment]
see: https://github.com/dccodecoffee/dccodecoffee.github.io/pull/8

**Comment by kalimar** [comment]
On it! Thanks!

**Comment by kalimar** [comment]
See PR https://github.com/NoVACodeCoffee/novacodecoffee.github.io/pull/11
